### ISSUE TITLE
这个脚本怎么用？

### ISSUE THREAD

**Issue by zaozaool** [everyx/vagrant-box-download-helper-everyx.user.js#1]
这个脚本怎么用？

**Comment by everyx** [comment]
这是一个 UserScript 脚本，你可以搜索一下你所用浏览器如何安装，如[这里](http://emulefans.com/userscript-on-various-browsers/)，chrome 应该是原生支持的，Firefox 需要安装扩展，比如 [scriptish](https://addons.mozilla.org/en-US/firefox/addon/scriptish/)，然后可以[访问这里安装](https://greasyfork.org/zh-CN/scripts/12435-vagrant-box-download-helper)

**Comment by zaozaool** [comment]
多谢
